services:
  baseballsim-apis:
    container_name: BaseballSimAPI
    hostname: BaseballSimAPI
    image: baseballsim.apis
    build:
      context: .
      dockerfile: ./BaseballSim.Apis/Dockerfile
    ports:
      - "7240:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
